font_family family="JetBrainsMono Nerd Font "
bold_font auto
italic_font auto
bold_italic_font auto

cursor_shape block
shell_integration no-cursor

background #141414

dynamic_background_opacity yes
# background_opacity 0.95
