#App launchers

bind = $mainMod, return, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, b, exec, brave
bind = $mainMod, R, exec, rofi -show drun -theme ~/.config/rofi/launcher.rasi 
bind = $mainMod, c, exec, ~/.config/hypr/scripts/clipboard.sh
bind = $mainMod, l, exec, hyprlock --immediate-render --no-fade-in
