# Window controls

bind = $mainMod, q, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, f, fullscreen
bind = $mainMod, P, pseudo,
bind = $mainMod, J, togglesplit,

# Focus movement with arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Focus movement with vim keys
bind = $mainMod SHIFT, h, movefocus, l
bind = $mainMod SHIFT, l, movefocus, r
bind = $mainMod SHIFT, k, movefocus, u
bind = $mainMod SHIFT, j, movefocus, d

# Move and resize windows with mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
