# Startup apps and background services

exec-once = waybar & hyprpaper & hypridle & mako
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Bluetooth applet
exec-once = blueman-applet
