# ~/.config/starship/starship.toml

add_newline = false
palette = "cyber"

format = """
[  ](fg:arch bg:seg1)[](fg:seg1 bg:seg2)\
$username\
$directory\
$git_status\
$git_branch\
$fill\
[](fg:seg1)\
[  $time ](fg:#FFD75F bg:seg1)\
$line_break\
$character
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[ $user ](fg:green bg:seg2)[](fg:seg2 bg:seg3)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
format = "[ $path ](fg:blue bg:seg3)[](fg:seg3)"

[time]
disabled = false
time_format = "%H:%M"
format = "$time"

[character]
success_symbol = "[❯](bold fg:arch)"
error_symbol   = "[❯](bold fg:red)"

[git_branch]
symbol = " "
format = " [on ](fg:#e6e6e6)[$symbol$branch](fg:#7aa2f7)"

[git_status]
format = " [$all_status$ahead_behind](fg:#ff9f1c)"

[palettes.cyber]
seg1 = "#2a2f3a"
seg2 = "#303746"
seg3 = "#3a4356"
seg4 = "#26324a"

text = "#e6e6e6"
cyan = "#00d2ff"
blue = "#5FAFFF"
arch = "#1793d1"
red  = "#ff4628"
green = "#39FF14"
